<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-19T14:45:39 IST" name="Suite" finished-at="2024-11-19T14:45:42 IST" duration-ms="3135">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.SubmitOrder()[pri:0, instance:PI.admin.ErrorValidationTest@f79e]" name="SubmitOrder" class="PI.admin.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-11-19T14:45:39 IST" name="Submit Order Test" finished-at="2024-11-19T14:45:39 IST" duration-ms="13">
    </test> <!-- Submit Order Test -->
    <test started-at="2024-11-19T14:45:39 IST" name="Error Validation" finished-at="2024-11-19T14:45:42 IST" duration-ms="3060">
      <class name="PI.admin.ErrorValidationTest">
        <test-method is-config="true" signature="launchingApplication()[pri:0, instance:PI.admin.ErrorValidationTest@f79e]" started-at="2024-11-19T14:45:39 IST" name="launchingApplication" finished-at="2024-11-19T14:45:42 IST" duration-ms="2261" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingApplication -->
        <test-method signature="SubmitOrder()[pri:0, instance:PI.admin.ErrorValidationTest@f79e]" started-at="2024-11-19T14:45:42 IST" name="SubmitOrder" finished-at="2024-11-19T14:45:42 IST" duration-ms="766" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect credentials or wrong password] but found [Incorrect credentials or wrong pass1@word]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect credentials or wrong password] but found [Incorrect credentials or wrong pass1@word]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PI.admin.ErrorValidationTest.SubmitOrder(ErrorValidationTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
      </class> <!-- PI.admin.ErrorValidationTest -->
    </test> <!-- Error Validation -->
  </suite> <!-- Suite -->
</testng-results>
